# Generated by Django 5.0.6 on 2024-06-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_view_results', 'User can access results page'), ('can_view_results_w_score', 'User can access page and check votes count')]},
        ),
    ]
